# Generated by Django 4.2.8 on 2023-12-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySplitterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='queue_position',
            field=models.IntegerField(default=0),
        ),
    ]
